export { default as header__logo } from './header__logo.svg'
export { default as header__search } from './header__search.svg'
export { default as intro__image } from './intro__image.png'
export { default as intro_b_image1 } from './intro_b_image1.png'
export { default as intro_b_image2 } from './intro_b_image2.png'
export { default as intro_b_image3 } from './intro_b_image3.png'
export { default as card } from './card.png'
export { default as card_bin } from './card_bin.svg'
export { default as card_starts } from './card_starts.png'
export { default as content__image } from './content__image.png'
export { default as facebook } from './facebook.svg'
export { default as twitter } from './twitter.svg'
export { default as instagram} from './instagram.svg'
export { default as oval } from './oval.svg'